# Generated by Django 2.0.6 on 2018-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7site', '0003_record_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='last_switch',
            field=models.IntegerField(default=0),
        ),
    ]
